comment:
  # header: "Please note the following requirement:"
  footer: "\
    ---\n\n
    > &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; Be sure to [join the community](https://slack.layer5.io), if you haven't yet and please leave a :star: [star on the project](../stargazers) :smile:
    "

labels:
  - name: framework/discourse
    labeled:
      issue:
        body: This issue has been labeled with 'framework/discourse'. Note that prior to commencing you need to create an account [here](https://staging-discuss.layer5.io/) and then ask for the admin access. After that start contributing to the discuss forum.
        action: open

  - name: issue/remind
    labeled:
      issue:
        body: Checking in... it has been awhile since we&#39;ve heard from you on this issue. Are you still working on it? Please let us know and please don&#39;t hesitate to contact a [MeshMate](https://layer5.io/community/meshmates/) or any other [community member](https://layer5.io/community/members) for assistance.
        action: open
      pr:
        body: Checking in... it has been awhile since we&#39;ve heard from you on this issue. Are you still working on it? Please let us know and please don&#39;t hesitate to contact a [MeshMate](https://layer5.io/community/meshmates/) or any other [community member](https://layer5.io/community/members) for assistance.
        action: open

  - name: issue/dco
    labeled:
      issue:
        body: "ðŸš¨ Alert! Git Police! We couldnâ€™t help but notice that one or more of your commits is missing a sign-off. _A what?_ A commit sign-off (your email address).\n\n
         To amend the commits in this PR with your signoff using the instructions provided in the DCO check above. \n\n
         To configure your dev environment to automatically signoff on your commits in the future, see [these instructions](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)."
        action: open
      pr:
        body: "ðŸš¨ Alert! Git Police! We couldnâ€™t help but notice that one or more of your commits is missing a sign-off. _A what?_ A commit sign-off (your email address).\n\n
         To amend the commits in this PR with your signoff using the instructions provided in the DCO check above. \n\n
         To configure your dev environment to automatically signoff on your commits in the future, see [these instructions](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)."
        action: open
