title: Layer5
author: Lee Calcote
email: community@layer5.io
name:  Layer5
description: "the service mesh community - making service meshes available to the rest of us.
 Open source software for management of service meshes.
 Allowing developers to focus on business logic, not infrastructure concerns.
 Empowering operators to confidentally run modern infrastructure."
url: "https://layer5.io"
baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty

parallax_image_one: assets/images/layer5-logo.gif #-header-large.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

portfolio_heading: Workshops
portfolio_type: cards

project_button: Github

session: Session

#Contact / Social
github: https://github.com/layer5io
medium: https://layer5.io
slack: http://slack.layer5.io/
blog: https://layer5.io/blog
docker: https://hub.docker.com/u/layer5/
youtube: https://www.youtube.com/channel/UCFL1af7_wdnhHXL1InzaMvA?sub_confirmation=1
twitter:
  card: summary
  username: layer5
  url: "https://twitter.com/layer5"
  image: "https://layer5.io/assets/images/layer5/5-dark-bg.png"

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: UA-2969471-4 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
# theme: minima
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

collections_dir: collections
collections:
  authors:
    output: true
  books:
    output: true
    permalink: /books/:title
  blogs:
    output: true
    permalink: /blog/:title/
  pages:
    output: true
  people:
    output: true
  projects:
    output: true
    permalink: /projects/:title
  topics:
    output: true
    permalink: /topics/:title
  workshops:
    output: true
    permalink: /workshops/:title
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/layer5/layer5-tag-linkedin.png
  - scope:
      type: pages
    values:
      layout: default
      body-class: left-sidebar
      sidebar: open
  - scope:
      type: books
    values:
      layout: default
      body-class: left-sidebar
      sidebar: open
    # Collection defaults

# Colors
layer5.gray: "#3c494f"
layer5.darkgreen: "#00b39f"
layer5.lightgreen: "#00d3a9"

## Reference - OSS this site uses:
    # Particles - http://www.fabiolamanna.it
    # Nav menu - https://github.com/vinnymoreira/stellarnav
    # Jekyll theme - https://github.com/jameshamann/jekyll-material-theme
    # https://github.com/VincentGarreau/particles.js
    # https://cssgradient.io
    # https://coolbackgrounds.io
    # Image view - https://jekyllcodex.org/without-plugin/lightbox/

## A message to have visitors acknowledge use of cookies (not currently used)
# cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.
# cookie_accept_message: Thank you. Enjoy!

## Skill icons from https://konpa.github.io/devicon/ (not currently used)
# icon_size: 50 # font-size of icons in px
# colored: colored # Leave blank for black and white icons

#skills: 
#    - name: docker
#   - name: android
#   - name: angularjs
#   - name: apache
#   - name: appcelerator
#   - name: apple
#   - name: atom
#   - name: babel
#   - name: backbonejs
#   - name: bitbucket
#   - name: bootstrap
#   - name: bower
#   - name: c
#   - name: chrome
#   - name: codeigniter
#   - name: coffescript
#   - name: confluence
#   - name: cplusplus
#   - name: csharp
#   - name: css3
#   - name: cucumber
#   - name: d3js
#   - name: debian
#   - name: devicon
#   - name: django
#   - name: docker
#   - name: doctrine
#   - name: dot-net
#   - name: drupal
#   - name: erlang
#   - name: facebook
#   - name: firefox
#   - name: foundation
#   - name: gatling
#   - name: gimp
#   - name: git
#   - name: github
#   - name: gitlab
#   - name: go
#   - name: google
#   - name: gradle
#   - name: grunt
#   - name: gulp
#   - name: heroku
#   - name: html5
#   - name: ie10
#   - name: illustrator
#   - name: inkscape
#   - name: itellij
#   - name: java
#   - name: jasmine
#   - name: javascript
#   - name: laravel
#   - name: less
#   - name: linux
#   - name: meteor
#   - name: mocha
#   - name: mongodb
#   - name: moodle
#   - name: mysql
#   - name: nginx
#   - name: nodejs
#   - name: nodewebkit
#   - name: oracle
#   - name: photoshop
#   - name: php
#   - name: phpstorm
#   - name: protractor
#   - name: postgresql
#   - name: python
#   - name: pycharm
#   - name: rails
#   - name: react
#   - name: redhat
#   - name: redis
#   - name: ruby
#   - name: rubymine
#   - name: safari
#   - name: sass
#   - name: sequelize
#    - name: slack
#   - name: sourcetree
#   - name: ssh
#   - name: swift
#   - name: symfony
#   - name: tomcat
#   - name: travis
#   - name: trello
#   - name: twitter
#   - name: typescript
#   - name: ubuntu
#   - name: vim
#   - name: visualstudio
#   - name: vuejs
#   - name: webpack
#   - name: webstorm
#   - name: windows8
#   - name: wordpress
#   - name: yii
#   - name: zend
