title: Layer 5
name: Lee Calcote
email: lee@calcotestudios.com
description: Characterizing and contrasting service meshes and related technologies.

baseurl: ""
url: ""

parallax_image_one: assets/images/cube.png #-header-large.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: "Using Istio Workshop"
project_one_description: A worshop containing ten labs on the Istio service mesh. First presented at DockerCon18. _See the resource links below._
project_one_url: https://github.com/leecalcote/istio-service-mesh-workshop
project_one_icon: location_on

# project_two: Second Project
# project_two_description: Describe your project!
# project_two_url: https://github.com/jameshamann/jekyll-material-theme
# project_two_icon: photo_camera


project_three: Third Project
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel


project_four: Fourth Project
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant

portfolio_heading: Workshops
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills: 
    - name: docker
#   - name: android
#   - name: angularjs
#   - name: apache
#   - name: appcelerator
#   - name: apple
#   - name: atom
#   - name: babel
#   - name: backbonejs
#   - name: bitbucket
#   - name: bootstrap
#   - name: bower
#   - name: c
#   - name: chrome
#   - name: codeigniter
#   - name: coffescript
#   - name: confluence
#   - name: cplusplus
#   - name: csharp
#   - name: css3
#   - name: cucumber
#   - name: d3js
#   - name: debian
#   - name: devicon
#   - name: django
#   - name: docker
#   - name: doctrine
#   - name: dot-net
#   - name: drupal
#   - name: erlang
#   - name: facebook
#   - name: firefox
#   - name: foundation
#   - name: gatling
#   - name: gimp
#   - name: git
#   - name: github
#   - name: gitlab
#   - name: go
#   - name: google
#   - name: gradle
#   - name: grunt
#   - name: gulp
#   - name: heroku
#   - name: html5
#   - name: ie10
#   - name: illustrator
#   - name: inkscape
#   - name: itellij
#   - name: java
#   - name: jasmine
#   - name: javascript
#   - name: laravel
#   - name: less
#   - name: linux
#   - name: meteor
#   - name: mocha
#   - name: mongodb
#   - name: moodle
#   - name: mysql
#   - name: nginx
#   - name: nodejs
#   - name: nodewebkit
#   - name: oracle
#   - name: photoshop
#   - name: php
#   - name: phpstorm
#   - name: protractor
#   - name: postgresql
#   - name: python
#   - name: pycharm
#   - name: rails
#   - name: react
#   - name: redhat
#   - name: redis
#   - name: ruby
#   - name: rubymine
#   - name: safari
#   - name: sass
#   - name: sequelize
#   - name: slack
#   - name: sourcetree
#   - name: ssh
#   - name: swift
#   - name: symfony
#   - name: tomcat
#   - name: travis
#   - name: trello
#   - name: twitter
#   - name: typescript
#   - name: ubuntu
#   - name: vim
#   - name: visualstudio
#   - name: vuejs
#   - name: webpack
#   - name: webstorm
#   - name: windows8
#   - name: wordpress
#   - name: yii
#   - name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/leecalcote/istio-service-mesh-workshop
medium: http://gingergeek.com
blog: http://gingergeek.com


baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
#url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thank you. Enjoy!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
