name: Build and Preview Site
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, edited, reopened]


jobs:
  build-deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          repository: 'layer5labs/layer5'

      - name: Install and Build ğŸ”§ 
        run: |
          npm install
          npm run build

      - name: Deploy and Preview ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          repository-name: "layer5labs/layer5"
          ssh-key: true
          branch: site${{ github.event.number }} # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
          target-folder: preview${{ github.event.number }}
          clean: false
