name: Build and Preview Site
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, edited, reopened]


jobs:
  build-deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build ğŸ”§ 
        run: |
          npm install
          npm run build

      - name: Deploy and Preview ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          git-config-name: Nikhil-Ladha
          git-config-email: nikhilladha1999@gmail.com
          repository-name: "layer5labs/layer5"
          token: ${{ secrets.PAT_PREVIEW }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: site${{ github.event.number }} # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
          target-folder: preview${{ github.event.number }}
          # clean: false
