name: Deploy Preview
on:
  workflow_run:
    workflows:
      - Build and Preview Site
    types:
      - completed

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Site dir
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          workflow: build-and-preview-site.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: public-dir

      - name: Unzip Site
        run: |
          rm -rf ./public
          unzip public-dir.zip
          rm -f public-dir.zip

      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: 'public'
          production-deploy: false
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Comment Deploy URL
        uses: ./.github/actions/comment-preview-on-pr
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          deploy_url: "${{ steps.netlify.outputs.deploy-url }}"

      - name: Audit URLs using Lighthouse for desktop
        # https://github.com/treosh/lighthouse-ci-action
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: ${{ steps.netlify.outputs.url }}
          budgetPath: ./.github/config/lighthouse-budget.json
          configPath: ./.github/config/lighthouse-config-desktop.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3

      - name: Audit URLs using Lighthouse for mobile
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: https://layer5.io/
          budgetPath: ./.github/config/lighthouse-budget.json
          configPath: ./.github/config/lighthouse-config-mobile.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
